### ISSUE TITLE
Cirrus Core 1.5.1 stuck - Connected to the API, waiting for node to initialize.

### ISSUE THREAD

**Issue by reinto** [stratisproject/CirrusCore#10]
After installing Cirrus Core 1.5.1 over 1.5.0 and removing data dirs to start syncing from scratch, I got to around 85% after which I've shut down the wallet and the laptop.

After a reboot of the laptop, now the Cirrus Core 1.5.1 installation is stuck at "Connected to the API. Waiting for node to initialize."
After clearing the data dirs again, except for the wallets and logs folder and peers.json file, I can log into the wallet and it starts syncing from scratch again. As expected.

**Comment by dev0tion** [comment]
Hi @reinto, this issue was fixed in 1.5.1. 
I expect that the CirrusD process was still running in the background when you installed 1.5.1, in that case the daemon would not get updated correctly.

Close the wallet, open task manager and make sure there's no "Stratis.CirrusD.exe" process still running and install 1.5.1 again.
You should not get that error again afterwards.

**Comment by reinto** [comment]
Yeah, that might have been the case. Later, I noticed that 1.5.0 was still installed beside 1.5.1 I uninstalled 1.5.0 manually and did a full resync. Would be nice though if the installer would check for a running cirrusD process upon installation.

Solved for me.
